# Generated by Django 4.1 on 2022-08-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_stocknotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocknotification",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
