# Generated by Django 4.0.4 on 2022-06-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/categories/subcategories'),
        ),
    ]
