# Generated by Django 4.1 on 2022-08-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_subcategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="suited_for",
            field=models.CharField(blank=True, default="any", max_length=16),
        ),
    ]
