# Generated by Django 4.1 on 2022-08-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_subcategory_suited_for"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategory",
            name="suited_for",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "male"),
                    ("female", "female"),
                    ("both", "both"),
                    ("any", "any"),
                ],
                default="any",
                max_length=16,
            ),
        ),
    ]
